version: '3'
services:
  jenkins:
    image: jenkinsci/blueocean
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
       - jenkins-data:/var/jenkins_home
       - jenkins-docker-certs:/certs/client
    networks:
       - jenkins

volumes:
  jenkins-docker-certs:
  jenkins-data:

networks:
  jenkins: